spring.application.name=demo
spring.datasource.url=jdbc:sqlite:C:/Users/nagao/Downloads/sqlite-tools-win-x64-3530300/equipment.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.thymeleaf.cache=false

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
